version: "3.8"

services:
  next-app:
    build:
      context: .
      dockerfile: ./next-app/Next.Dockerfile
    container_name: next-app
    restart: always
    ports:
      - '3000:3000'  # Expose Next.js app on port 3000
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: quizzly
    environment:
      POSTGRES_DB: quizzly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  report-app:
    build:
      context: ./report-app
    container_name: report-app
    restart: always
    ports:
      - "3002:3000" # Expose report-app on port 3002
    environment:
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - AWS_KEY_ID=${AWS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

volumes:
  postgres_data:
